// Pure-JS SHA-256 suite for the sprint engine's dialect-neutral core.
//
// Runs as: node skills/sprint-runner/tools/tests/test-sha256.js
//
// Plain Node, no test framework, no dependencies beyond the module under
// test. Covers one function: specEngineSha256(str), a from-scratch
// SHA-256 implementation (FIPS 180-4) taking a JS string and returning the
// lowercase hex digest of that string's UTF-8 encoding. Not named in
// SPEC_SCHEMA.md -- this todo delivers only the hash function and its test
// suite, ahead of the spill-verification caller that will use it.
//
// All digests below were generated from node's own "crypto" module,
// OUTSIDE this suite and outside engine-core.js, and hard-coded here as
// the expected values: `node -e "console.log(require('crypto')
// .createHash('sha256').update(Buffer.from(STR, 'utf8')).digest('hex'))"`
// for each STR. The four vectors from the abc/empty/two-block/spill-
// threshold group and the boundary-length and non-ASCII groups were all
// independently confirmed this way before this suite was written.

'use strict';

const { specEngineSha256 } = require('../engine-core.js');

let passCount = 0;
let failCount = 0;

function check(description, condition) {
  if (condition) {
    passCount += 1;
  } else {
    failCount += 1;
    console.error('FAIL: ' + description);
  }
}

// ===========================================================================
// specEngineSha256(str) -- NIST/well-known test vectors
// ===========================================================================

// -- hit case: the standard one-block "abc" vector, from node crypto ------
{
  const digest = specEngineSha256('abc');
  check(
    'sha256("abc") matches the node-crypto-generated digest',
    digest === 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'
  );
}

// -- edge case: the empty string, from node crypto -------------------------
{
  const digest = specEngineSha256('');
  check(
    'sha256("") matches the node-crypto-generated digest',
    digest === 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
  );
}

// -- hit case: the standard two-block vector, from node crypto -------------
{
  const digest = specEngineSha256('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq');
  check(
    'sha256 of the two-block NIST-style message matches the node-crypto-generated digest',
    digest === '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1'
  );
}

// -- edge case: the engine's spill-threshold size class, from node crypto -
{
  const digest = specEngineSha256('A'.repeat(41628));
  check(
    'sha256 of a 41628-byte all-ASCII string (the spill-threshold size class) matches the node-crypto-generated digest',
    digest === '36ca5c730655bc352a8b0d0d5ca92b5f468eddc0f66fa0948ab3ca1bb17dae63'
  );
}

// ===========================================================================
// specEngineSha256(str) -- padding boundary edge cases (self-generated)
// ===========================================================================
//
// SHA-256 pads a message to a multiple of 64 bytes, appending a 0x80 byte
// then zero bytes until the length is congruent to 56 mod 64, then an
// 8-byte bit-length field. Lengths 55/56/57/63/64/65 straddle that
// boundary: 55 is the largest length that pads within the FIRST block
// (55 + 1 = 56, exactly the pre-length-field cutoff); 56 is the smallest
// length that spills the 0x80-plus-padding into a SECOND block; 57 is a
// mid-range remainder length inside that second block, one padding-loop
// iteration past 56, added to exercise the zero-fill loop on an ordinary
// (non-edge) remainder rather than only its two boundary endpoints.
// 63/64/65 hit the NEXT 64-byte block boundary, but not "the same way" as
// each other -- each lands in a distinct one of three padding branches:
// for 63, the 0x80 marker itself exactly fills the last byte of the first
// block, so the zero-padding and the 8-byte length field occupy the whole
// second block; for 64, the 64 data bytes alone exactly fill the first
// block, so the marker is the very first byte that opens the second
// block; for 65, one data byte already spills past the first block before
// the marker, so the marker itself lands as the second byte of the second
// block. All six digests below were generated by:
//   node -e "console.log(require('crypto').createHash('sha256')
//     .update(Buffer.from('B'.repeat(N), 'utf8')).digest('hex'))"
// once per N in {55, 56, 57, 63, 64, 65}.

{
  const digest = specEngineSha256('B'.repeat(55));
  check(
    'sha256 of a 55-byte string (largest length padding within the first block) matches the node-crypto-generated digest',
    digest === '1eed5900533b34bb08a62c072a0b0a67058b181b53a8f6e14d3d88d1d78fbe2b'
  );
}

{
  const digest = specEngineSha256('B'.repeat(56));
  check(
    'sha256 of a 56-byte string (smallest length spilling padding into a second block) matches the node-crypto-generated digest',
    digest === '821c30ffb748ac6d776ad4972a6cbc7ca32e6aaf63b68808e7fe92321dfbb6b8'
  );
}

{
  const digest = specEngineSha256('B'.repeat(57));
  check(
    'sha256 of a 57-byte string (a mid-range zero-padding remainder, not a boundary endpoint) matches the ' +
      'node-crypto-generated digest',
    digest === '87ffc74a239a01768fcc097cf3cf842817e0e4b9e7cafbb03fb7ca5ada3ca3f3'
  );
}

{
  const digest = specEngineSha256('B'.repeat(63));
  check(
    'sha256 of a 63-byte string matches the node-crypto-generated digest',
    digest === '3a34cb82d88093a2af090dd7eecbef323bfd2a9737ac7bb79240ca4bba357214'
  );
}

{
  const digest = specEngineSha256('B'.repeat(64));
  check(
    'sha256 of a 64-byte string (exactly one full block before padding) matches the node-crypto-generated digest',
    digest === 'c422e7070cb1cb455b5de9afee0d975e303d0239c72030cd7414ab5c382d3ae8'
  );
}

{
  const digest = specEngineSha256('B'.repeat(65));
  check(
    'sha256 of a 65-byte string (one byte past a full block) matches the node-crypto-generated digest',
    digest === '3db14a3b436f09c012eaf07ed03300ef30f349936a414abe4d3946d3ae578170'
  );
}

// ===========================================================================
// specEngineSha256(str) -- UTF-8 byte-count branch coverage (self-generated)
// ===========================================================================
//
// specEngineUtf8Encode picks a 1/2/3/4-byte encoding per code point by a
// chain of "codePoint <= X" comparisons. The vectors above (all-ASCII
// strings, and the emoji pair below) only exercise the 1-byte and 4-byte
// branches; nothing above this section pins the 2-byte or 3-byte branches
// on their own, or the four codePoint thresholds those branches turn on.
// This section closes that gap directly: one code point squarely inside
// the 2-byte range plus that code point inside a multi-character word (to
// prove the byte-count decision is made per code point, not smeared across
// the whole string), the LAST code point the 2-byte branch accepts
// (U+07FF) immediately followed by the FIRST code point the 3-byte branch
// accepts (U+0800) -- the exact boundary a mutant widening or narrowing
// the "codePoint <= 0x7ff" comparison by one would cross -- the same
// last/first pairing at the 3-byte/4-byte boundary (U+FFFF, the highest
// code point representable as a single UTF-16 code unit, and U+10000, the
// lowest code point needing a surrogate pair), and one string mixing all
// four byte-count classes (plain ASCII, 2-byte, 3-byte, 4-byte) back to
// back in a single input.
//
// All seven expected digests below were generated by:
//   node -e "console.log(require('crypto').createHash('sha256')
//     .update(Buffer.from(STR, 'utf8')).digest('hex'))"
// with STR set to each of the seven strings below, in turn (each STR
// built from \u escapes in the generating script, the same code points
// expressed as \u escapes in this file's source).

{
  const digest = specEngineSha256('\u00e9');
  check(
    'sha256 of a single 2-byte-branch code point (U+00E9, e-acute) alone matches the node-crypto-generated digest',
    digest === '4a99557e4033c3539de2eb65472017cad5f9557f7a0625a09f1c3f6e2ba69c4c'
  );
}

{
  const digest = specEngineSha256('caf\u00e9');
  check(
    'sha256 of a word containing a 2-byte-branch code point mid-string ("caf\u00e9") matches the ' +
      'node-crypto-generated digest, proving the byte-count decision is made per code point',
    digest === '850f7dc43910ff890f8879c0ed26fe697c93a067ad93a7d50f466a7028a9bf4e'
  );
}

{
  const digest = specEngineSha256('\u07ff');
  check(
    'sha256 of U+07FF (the LAST code point the 2-byte branch accepts) matches the node-crypto-generated digest',
    digest === 'c57c6175c9087b0c1f7f849c840c8d1ab5b0c32163ffac03fb9f1913f222516d'
  );
}

{
  const digest = specEngineSha256('\u0800');
  check(
    'sha256 of U+0800 (the FIRST code point the 3-byte branch accepts, one past U+07FF) matches the ' +
      'node-crypto-generated digest',
    digest === 'a36ae1af6063cc9281d4010e979a1e3fd3d9ee3e804b7093d2b00f6ee6388bec'
  );
}

{
  const digest = specEngineSha256('\uffff');
  check(
    'sha256 of U+FFFF (the LAST code point representable as a single UTF-16 code unit, the top of the ' +
      '3-byte branch) matches the node-crypto-generated digest',
    digest === '2c34e62119d9c5fc3aa11640bd7945d6bf309acc6e99d8054f54ae5110e343f6'
  );
}

{
  const digest = specEngineSha256('\ud800\udc00');
  check(
    'sha256 of U+10000 (the FIRST code point needing a surrogate pair, the bottom of the 4-byte branch, ' +
      'one past U+FFFF) matches the node-crypto-generated digest',
    digest === '31237b174ba6047a15db0d343ad9550da611b7b7bce867a23522f81a05df3eda'
  );
}

{
  const digest = specEngineSha256('A\u00e9\u0800\ud800\udc00');
  check(
    'sha256 of one string mixing all four UTF-8 byte-count classes back to back (ASCII, 2-byte, 3-byte, ' +
      '4-byte) matches the node-crypto-generated digest',
    digest === 'a9f56c5db2f674b03126c21a912f7a7b9ac0cd073c4308c8df6af8afc58c109b'
  );
}

// ===========================================================================
// specEngineSha256(str) -- non-ASCII / surrogate-pair edge case (self-generated)
// ===========================================================================
//
// The character U+1F600 ("grinning face") is a code point above U+FFFF --
// exercises the 4-byte UTF-8 encoding branch and the high/low surrogate
// combination specEngineUtf8Encode performs by hand. Expressed only as a
// \u escape sequence in the source string below (never a literal emoji
// character) to keep this file ASCII-only. Digest generated by:
//   node -e "console.log(require('crypto').createHash('sha256')
//     .update(Buffer.from('hello ' + String.fromCodePoint(0x1F600) +
//     ' world', 'utf8')).digest('hex'))"

{
  const digest = specEngineSha256('hello \ud83d\ude00 world');
  check(
    'sha256 of a string containing a surrogate-pair emoji (U+1F600) matches the node-crypto-generated digest',
    digest === 'de3e9c1384cf7633c84f01096738945171d5aec0d0d7e11eef3f990374df96b5'
  );
}

// ===========================================================================
// specEngineSha256(str) -- repeat-call determinism
// ===========================================================================
//
// No shared mutable state between calls: the same input hashed twice must
// return the identical digest both times, and different inputs interleaved
// between two calls on the same input must not perturb either result. A
// prior suite in this repo caught a lastIndex statefulness bug from a
// caller-shared global-flag RegExp (see test-primitives.js); this fixture
// is the sha256 analog of that same class of check.

{
  const first = specEngineSha256('repeat-me');
  const second = specEngineSha256('repeat-me');
  check('sha256 of the same input twice, back to back, returns identical digests', first === second);
  check(
    'sha256 of "repeat-me" matches the node-crypto-generated digest',
    first === '8a8711d8a6a66988a8b6880314085ef16fee712e6c8e8800ae052971788ac3a9'
  );
}

{
  const before = specEngineSha256('interleave-a');
  const otherOne = specEngineSha256('interleave-b');
  const otherTwo = specEngineSha256('abc');
  const after = specEngineSha256('interleave-a');
  check('sha256 of "interleave-a" is unaffected by different calls interleaved after it', before === after);
  check(
    'sha256 of "interleave-a" matches the node-crypto-generated digest',
    before === '1fbc60c61678e5035b5f7be7348e4ae4201fa99fc31b54d238b1073aee94b048'
  );
  check(
    'the interleaved "interleave-b" call still returns its own correct digest',
    otherOne === 'ddc75dbf712f79d8179ea7008695faba8ac9190c6f4c81fd54052828ca7b1b38'
  );
  check(
    'the interleaved "abc" call still returns the same digest as the standalone "abc" case above',
    otherTwo === 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'
  );
}

// ===========================================================================
// specEngineSha256(str) -- unpaired-surrogate substitution (self-generated)
// ===========================================================================
//
// node's own "crypto" module hashes a string by first running it through
// Buffer.from(str, 'utf8'), which replaces ANY unpaired surrogate code
// unit -- a high surrogate (\ud800-\udbff) not immediately followed by a
// low surrogate, or a low surrogate not immediately preceded by a high
// surrogate -- with U+FFFD (the replacement character, bytes EF BF BD)
// before encoding. specEngineUtf8Encode matches that substitution by
// design: this function exists to verify spilled text against digests of
// on-disk bytes, and a UTF-8 file write performs the same substitution, so
// matching node's behavior (rather than encoding the lone surrogate's own
// numeric value as an isolated 3-byte sequence) is the correct property to
// pin here, not an edge case to leave undefined.
//
// All five expected digests below were generated by:
//   node -e "console.log(require('crypto').createHash('sha256')
//     .update(Buffer.from(STR, 'utf8')).digest('hex'))"
// with STR set to each of the five strings below, in turn.

{
  const digest = specEngineSha256('\ud800');
  check(
    'sha256 of a lone high surrogate substitutes U+FFFD, matching the node-crypto-generated digest',
    digest === '83d544ccc223c057d2bf80d3f2a32982c32c3c0db8e2674820da5064783fb097'
  );
}

{
  const digest = specEngineSha256('\udc00');
  check(
    'sha256 of a lone low surrogate substitutes U+FFFD, matching the node-crypto-generated digest',
    digest === '83d544ccc223c057d2bf80d3f2a32982c32c3c0db8e2674820da5064783fb097'
  );
}

{
  const highLone = specEngineSha256('\ud800');
  const lowLone = specEngineSha256('\udc00');
  check(
    'a lone high surrogate and a lone low surrogate both substitute the SAME U+FFFD digest',
    highLone === lowLone
  );
}

{
  const digest = specEngineSha256('\ud800A');
  check(
    'sha256 of a high surrogate followed by a non-low-surrogate character substitutes U+FFFD for the ' +
      'surrogate and encodes the following character normally, matching the node-crypto-generated digest',
    digest === '1b6d8a78363cf390895eba876b9fefb99d73506bb40fe31c4efeb2b58f7fe1fc'
  );
}

{
  const digest = specEngineSha256('\ud800\ud800');
  check(
    'sha256 of two consecutive lone high surrogates substitutes U+FFFD for EACH code unit independently ' +
      '(not once for the whole run), matching the node-crypto-generated digest',
    digest === '52793f8dc1d85e409f8c88be99d8b31d58f676246340150f406289e04a11151e'
  );
}

{
  const digest = specEngineSha256('\ud83d\ude00\udc00');
  check(
    'sha256 of a well-formed surrogate pair immediately followed by a lone low surrogate encodes the pair ' +
      'normally (proving the pairing logic does not mis-consume) and substitutes U+FFFD only for the ' +
      'trailing lone surrogate, matching the node-crypto-generated digest',
    digest === '43c07ec4819e4eb64f724ac552e7587fe21ce3110ed29797be89a927753b6578'
  );
}

console.log(passCount + ' passed, ' + failCount + ' failed');
process.exit(failCount === 0 ? 0 : 1);
